package com.au.sofico.dao;
/*package com.sofico.au.dao;

import javax.persistence.Entity;

// Generated 01/10/2016 2:48:47 PM by Hibernate Tools 3.5.0.Final

*//**
 * SsaEmployeeParkingMapping generated by hbm2java
 *//*
@Entity
public class SsaEmployeeParkingMappingEntity implements java.io.Serializable {

	private int ssaEmployeeParkingMappingId;
	private SsaEmployeesEntity ssaEmployees;
	private SsaParkingSpotsEntity ssaParkingSpots;

	public SsaEmployeeParkingMappingEntity() {
	}

	public SsaEmployeeParkingMappingEntity(int ssaEmployeeParkingMappingId) {
		this.ssaEmployeeParkingMappingId = ssaEmployeeParkingMappingId;
	}

	public SsaEmployeeParkingMappingEntity(int ssaEmployeeParkingMappingId, SsaEmployeesEntity ssaEmployees,
			SsaParkingSpotsEntity ssaParkingSpots) {
		this.ssaEmployeeParkingMappingId = ssaEmployeeParkingMappingId;
		this.ssaEmployees = ssaEmployees;
		this.ssaParkingSpots = ssaParkingSpots;
	}

	public int getSsaEmployeeParkingMappingId() {
		return this.ssaEmployeeParkingMappingId;
	}

	public void setSsaEmployeeParkingMappingId(int ssaEmployeeParkingMappingId) {
		this.ssaEmployeeParkingMappingId = ssaEmployeeParkingMappingId;
	}

	public SsaEmployeesEntity getSsaEmployees() {
		return this.ssaEmployees;
	}

	public void setSsaEmployees(SsaEmployeesEntity ssaEmployees) {
		this.ssaEmployees = ssaEmployees;
	}

	public SsaParkingSpotsEntity getSsaParkingSpots() {
		return this.ssaParkingSpots;
	}

	public void setSsaParkingSpots(SsaParkingSpotsEntity ssaParkingSpots) {
		this.ssaParkingSpots = ssaParkingSpots;
	}

}
*/