package com.au.sofico.dao;
// Generated 01/10/2016 2:48:47 PM by Hibernate Tools 3.5.0.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * SsaParkingSpots generated by hbm2java
 */
@Entity
@Table(name = "ssa_parking_spots", catalog = "ssaparking")
public class SsaParkingSpotsEntity implements java.io.Serializable {
	
	@Column(name = "ssa_employee_id", unique = true, nullable = false)
	private int ssaEmployeesId;
	public int getSsaEmployeesId() {
		return ssaEmployeesId;
	}

	public void setSsaEmployeesId(int ssaEmployeesId) {
		this.ssaEmployeesId = ssaEmployeesId;
	}

	@Column(name = "ssa_employee_name")
	private String ssaEmployeeName;

	@Id
	@GeneratedValue(strategy=GenerationType.AUTO)
	@Column(name = "ssa_parking_spots_id", unique = true, nullable = false)
	private int ssaParkingSpotsId;

	@ManyToMany(mappedBy = "ssaParkingSpotses") // name of the entity in the
												// ssaEmployeeEntity
	private Set<SsaEmployeesEntity> ssaEmployees = new HashSet<>(0);
	@Column(name = "ssa_parking_number")
	private String ssaParkingNumber;

	@Column(name = "is_special_parking_spot")
	private Integer isSpecialParkingSpot;
	// private Set<SsaEmployeeParkingMappingEntity> ssaEmployeeParkingMappings =
	// new HashSet<SsaEmployeeParkingMappingEntity>(0);

	@Column(name = "is_original_owner")
	private Integer isOriginalOwner;

	public Integer getIsOriginalOwner() {
		return isOriginalOwner;
	}

	public void setIsOriginalOwner(Integer isOriginalOwner) {
		this.isOriginalOwner = isOriginalOwner;
	}

	public SsaParkingSpotsEntity() {
	}

	public SsaParkingSpotsEntity(Set<SsaEmployeesEntity> ssaEmployees, String ssaParkingNumber,
			Integer isSpecialParkingSpot, Integer isOriginalOwner
	// ,Set<SsaEmployeeParkingMappingEntity> ssaEmployeeParkingMappings
	) {
		this.ssaEmployees = ssaEmployees;
		this.ssaParkingNumber = ssaParkingNumber;
		this.isSpecialParkingSpot = isSpecialParkingSpot;
		this.isOriginalOwner = isOriginalOwner;
		// this.ssaEmployeeParkingMappings = ssaEmployeeParkingMappings;
	}

	public Integer getSsaParkingSpotsId() {
		return this.ssaParkingSpotsId;
	}

	public void setSsaParkingSpotsId(Integer ssaParkingSpotsId) {
		this.ssaParkingSpotsId = ssaParkingSpotsId;
	}

	public Set<SsaEmployeesEntity> getSsaEmployees() {
		return this.ssaEmployees;
	}

	public void setSsaEmployees(Set<SsaEmployeesEntity> ssaEmployees) {
		this.ssaEmployees = ssaEmployees;
	}

	public String getSsaParkingNumber() {
		return this.ssaParkingNumber;
	}

	public void setSsaParkingNumber(String ssaParkingNumber) {
		this.ssaParkingNumber = ssaParkingNumber;
	}

	public Integer getIsSpecialParkingSpot() {
		return this.isSpecialParkingSpot;
	}

	public void setIsSpecialParkingSpot(Integer isSpecialParkingSpot) {
		this.isSpecialParkingSpot = isSpecialParkingSpot;
	}

	/*
	 * public Set<SsaEmployeeParkingMappingEntity>
	 * getSsaEmployeeParkingMappings() { return this.ssaEmployeeParkingMappings;
	 * }
	 * 
	 * public void
	 * setSsaEmployeeParkingMappings(Set<SsaEmployeeParkingMappingEntity>
	 * ssaEmployeeParkingMappings) { this.ssaEmployeeParkingMappings =
	 * ssaEmployeeParkingMappings; }
	 */

}
