package com.au.sofico.dao.entity;
// Generated 20/11/2016 9:24:01 AM by Hibernate Tools 3.5.0.Final

/**
 * SsaEmployeeParkingMapping generated by hbm2java
 */
public class SsaEmployeeParkingMapping implements java.io.Serializable {


	private SsaEmployees ssaEmployees;
	private SsaParkingSpots ssaParkingSpots;

	public SsaEmployeeParkingMapping() {
	}

	

	public SsaEmployeeParkingMapping( SsaEmployees ssaEmployees,
			SsaParkingSpots ssaParkingSpots) {
		
		this.ssaEmployees = ssaEmployees;
		this.ssaParkingSpots = ssaParkingSpots;
	}

	

	

	public SsaEmployees getSsaEmployees() {
		return this.ssaEmployees;
	}

	public void setSsaEmployees(SsaEmployees ssaEmployees) {
		this.ssaEmployees = ssaEmployees;
	}

	public SsaParkingSpots getSsaParkingSpots() {
		return this.ssaParkingSpots;
	}

	public void setSsaParkingSpots(SsaParkingSpots ssaParkingSpots) {
		this.ssaParkingSpots = ssaParkingSpots;
	}

}
