package com.au.sofico.dao.entity;
// Generated 22/04/2017 1:11:51 PM by Hibernate Tools 3.5.0.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * SsaEmployeeParkingMapping generated by hbm2java
 */
@Entity
@Table(name = "ssa_employee_parking_mapping", catalog = "ssaparking")
public class SsaEmployeeParkingMapping implements java.io.Serializable {

	private SsaEmployeeParkingMappingId id;
	
	
	
	private SsaEmployees ssaEmployees;
	private SsaParkingSpots ssaParkingSpots;

	
	
	
	public SsaEmployeeParkingMapping() {
	}

	public SsaEmployeeParkingMapping(SsaEmployeeParkingMappingId id) {
		this.id = id;
	}

	public SsaEmployeeParkingMapping(SsaEmployeeParkingMappingId id, SsaEmployees ssaEmployees,
			SsaParkingSpots ssaParkingSpots) {
		this.id = id;
		this.ssaEmployees = ssaEmployees;
		this.ssaParkingSpots = ssaParkingSpots;
		
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "ssaEmployeeId", column = @Column(name = "ssa_employee_id")),
			@AttributeOverride(name = "ssaParkingSpotId", column = @Column(name = "ssa_parking_spot_id")) })
	public SsaEmployeeParkingMappingId getId() {
		return this.id;
	}

	public void setId(SsaEmployeeParkingMappingId id) {
		this.id = id;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ssa_employee_id", insertable = false, updatable = false)
	public SsaEmployees getSsaEmployees() {
		return this.ssaEmployees;
	}

	public void setSsaEmployees(SsaEmployees ssaEmployees) {
		this.ssaEmployees = ssaEmployees;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ssa_parking_spot_id", insertable = false, updatable = false)
	public SsaParkingSpots getSsaParkingSpots() {
		return this.ssaParkingSpots;
	}

	public void setSsaParkingSpots(SsaParkingSpots ssaParkingSpots) {
		this.ssaParkingSpots = ssaParkingSpots;
	}

}
