package com.au.sofico.dao.entity;

import javax.persistence.Column;
import javax.persistence.Embeddable;



/**
 * SsaEmployeeParkingMappingId generated by hbm2java
 */
@Embeddable
public class SsaEmployeeParkingMappingId implements java.io.Serializable {

	private Integer ssaEmployeeId;
	private Integer ssaParkingSpotId;
	

	public SsaEmployeeParkingMappingId() {
	}

	public SsaEmployeeParkingMappingId(Integer ssaEmployeeId, Integer ssaParkingSpotId) {
		this.ssaEmployeeId = ssaEmployeeId;
		this.ssaParkingSpotId = ssaParkingSpotId;
		
	}

	@Column(name = "ssa_employee_id")
	public Integer getSsaEmployeeId() {
		return this.ssaEmployeeId;
	}

	public void setSsaEmployeeId(Integer ssaEmployeeId) {
		this.ssaEmployeeId = ssaEmployeeId;
	}

	@Column(name = "ssa_parking_spot_id")
	public Integer getSsaParkingSpotId() {
		return this.ssaParkingSpotId;
	}

	public void setSsaParkingSpotId(Integer ssaParkingSpotId) {
		this.ssaParkingSpotId = ssaParkingSpotId;
	}

	

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SsaEmployeeParkingMappingId))
			return false;
		SsaEmployeeParkingMappingId castOther = (SsaEmployeeParkingMappingId) other;

		return ((this.getSsaEmployeeId() == castOther.getSsaEmployeeId())
				|| (this.getSsaEmployeeId() != null && castOther.getSsaEmployeeId() != null
						&& this.getSsaEmployeeId().equals(castOther.getSsaEmployeeId())))
				&& ((this.getSsaParkingSpotId() == castOther.getSsaParkingSpotId())
						|| (this.getSsaParkingSpotId() != null && castOther.getSsaParkingSpotId() != null
								&& this.getSsaParkingSpotId().equals(castOther.getSsaParkingSpotId())))
				;
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getSsaEmployeeId() == null ? 0 : this.getSsaEmployeeId().hashCode());
		result = 37 * result + (getSsaParkingSpotId() == null ? 0 : this.getSsaParkingSpotId().hashCode());
	
		return result;
	}

}
