/*package com.au.sofico.dao.entity;
// Generated 07/02/2017 8:43:12 PM by Hibernate Tools 3.5.0.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.OneToOne;
import javax.persistence.Table;

*//**
 * SsaEmployeeParkingMapping generated by hbm2java
 *//*
@Entity
@Table(name = "ssa_employee_parking_mapping", catalog = "ssaparking")
public class SsaEmployeeParkingMapping implements java.io.Serializable {

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "ssa_employee_parking_id", unique = true, nullable = false)
	private Integer ssaEmployeeParkingId;
	
	@OneToOne
	@JoinTable(name = "ssa_employee_parking_mapping", 
	joinColumns = @JoinColumn(name = "ssa_parking_spots_id"))
	private SsaParkingSpots ssaParkingSpots;
	
	@OneToOne
	@JoinTable(name = "ssa_employee_parking_mapping", 
	joinColumns = @JoinColumn(name = "ssa_employees_id"))
	private SsaEmployees ssaEmployees;

	public SsaEmployeeParkingMapping() {
	}

	public SsaEmployeeParkingMapping(SsaParkingSpots ssaParkingSpots, SsaEmployees ssaEmployees) {
		this.ssaParkingSpots = ssaParkingSpots;
		this.ssaEmployees = ssaEmployees;
	}

	public Integer getSsaEmployeeParkingId() {
		return this.ssaEmployeeParkingId;
	}

	public void setSsaEmployeeParkingId(Integer ssaEmployeeParkingId) {
		this.ssaEmployeeParkingId = ssaEmployeeParkingId;
	}

	public SsaParkingSpots getSsaParkingSpots() {
		return this.ssaParkingSpots;
	}

	public void setSsaParkingSpots(SsaParkingSpots ssaParkingSpots) {
		this.ssaParkingSpots = ssaParkingSpots;
	}

	public SsaEmployees getSsaEmployees() {
		return this.ssaEmployees;
	}

	public void setSsaEmployees(SsaEmployees ssaEmployees) {
		this.ssaEmployees = ssaEmployees;
	}

}
*/